# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ChangingFond # 网站标题
subtitle: 活着，努力着，并收获着快乐 # 网站副标题
description:                       # 网站描述
author: ChangingFond  # 网站作者
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.fcj.one
root: /
# permalink: :year/:month/:day/:title/
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - googlebd03028478f9b467.html
  - collection/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# BaiduSitemap
baidusitemap:
  path: baidusitemap.xml

# Sitemap
sitemap:
  path: sitemap.xml

# Local search
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## Muse,Mist
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:ChangingFond/ChangingFond.github.io.git  #同步到GitHub
    vps: fcj@142.11.206.186:hexo.git,master  #同步到自己的VPS
  branch: master
  message: Hexo Blog updated - {{ now('YYYY-MM-DD HH:mm:ss') }})
